POST  http://localhost:3002/api/chatgpt
Content-Type: application/json

{
    "prompt" : "pretend that you are a less inteligent individual believing in conspiracy theories. Tell me some of the outrages things you believe in."
}